ghga-de/datameta

datameta/__init__.py, datameta/models/__init__.py, datameta/models/db.py, datameta/security.py, datameta/views/account.py, datameta/views/admin.py, datameta/views/home.py, datameta/views/login.py, datameta/views/submit.py, datameta/views/view.py
* Adds API key based auth. API keys are stored in a new database table `apikeys`.
* Clean up the `security` module
=> Add API Key Auth

datameta/models/db.py, datameta/scripts/initialize_db.py, datameta/security.py, datameta/views/forgot.py, datameta/views/login.py, datameta/views/setpass.py
* Moves hash functions to security module
* Changes datatype of pwhash column
=> Refactor password handling

.gitignore, datameta.compose.yml
added nginx reverse proxy with integrated letsencrypt for datameta app
=> Issue 62 and Issue 63

.gitignore, datameta.compose.yml
=> Revert "Issue 62 and Issue 63"

.gitignore, deploy/compose-metadata-w-proxy.yml, deploy/datameta_with_proxy.yml
Added nginx reverse proxy with letsencrypt for datameta app
=> Issues 62 and 63

datameta/api/apikeys.py, datameta/api/openapi.yaml, datameta/errors.py, datameta/security.py
- store Apikey as hash in database
- template for custom errors, usage:
```
from ..errors import ValidationError
...
raise ValidationError("my message")
```
- use ApiKey label and user side id
=> Hash token

datameta/api/metadatasets.py, datameta/api/openapi.yaml, datameta/errors.py, datameta/linting.py
Preview of validation for single metadataset
=> Metadata rest

datameta/resource.py
=> Remove debug code

datameta/api/apikeys.py, datameta/security.py
Tokens are hashed using SHA256. The hash is stored in the DB. The unhashed token is handed out to the user. Once a user tries to authenticate with that token. The token is hashed to search for the corresponding entry in the DB.
=> refactor token hashing

datameta/templates/layout.pt, datameta/templates/login.pt
Quick fix to make button stacking at least look properly
=> Adjust login button margins

datameta/api/apikeys.py, datameta/api/files.py, datameta/api/groups.py, datameta/api/metadatasets.py, datameta/api/openapi.yaml, datameta/api/submissions.py, datameta/errors.py, datameta/resource.py, tests/integration/test_apikeys.py
* Fixes #157 
* Refactoring of entity IDs
=> Refactor dual ID Handling in API, Fix error in submission validation

datameta/api/metadata.py, datameta/api/openapi.yaml, datameta/static/js/fileupload.js, datameta/static/js/submit.js, datameta/templates/submit.pt
Comes with another API definition change unfortunately, I did some bad attribute renaming before.
=> Add help information about metadata

datameta/static/js/account.js, datameta/static/js/admin.js, datameta/templates/admin.pt, datameta/views/admin.py
-> Added Group and User Tabs in the Admin View
-> Added Possibilities to Change user admin & enabled settings
-> Added Possibilities to change groups
-> Added Possibilities to change user and group names
=> Admin view

datameta/static/js/admin.js, datameta/views/admin.py
=> Should fix group request problems

datameta/api/users.py, datameta/static/js/admin.js, datameta/templates/admin.pt, datameta/views/admin.py, datameta/views/register.py
Fixes #220
Makes ids in the account requests restful
Also fixes group change problems
=> IDs are now restfull for account requests.

datameta/linting.py, datameta/samplesheet.py, datameta/views/submit.py
To be (continued and) merged after #245
=> Remove legacy code

datameta/templates/layout.pt
Using the same condition as in storage.py:34
=> Demo Mode is now viewed correctly

datameta/static/js/admin.js, datameta/templates/admin.pt
* Recalculate column widths after user table was loaded
* Make boolean columns sortable
* Fix missing CSS include on admin page (datatables bootstrap 5)
* Enable searching for users table
=> Minor admin UI fixes

datameta/api/ui/__init__.py, datameta/api/ui/view.py, datameta/static/js/view.js, datameta/templates/submit.pt, datameta/templates/view.pt
Adds a table of all submitted metadata to the "view data" page. Extraction of (raw) data is not possible at this stage.
=> Add 'view data' functionality to the web ui

datameta/api/groups.py, datameta/api/ui/admin.py
=> Fixissue 319

datameta/__init__.py, datameta/api/appsettings.py, datameta/api/register.py, datameta/api/ui/admin.py, datameta/api/ui/forgot.py, datameta/defaults/appsettings.yaml, datameta/models/__init__.py, datameta/models/db.py, datameta/scripts/initialize_db.py, datameta/settings.py, datameta/views/default.py, tests/integration/__init__.py, tests/integration/utils.py
* Defaults defined in yaml file. Missing application settings are set automatically upon launch
* Rename class
=> Refactor Application Settings

datameta/api/ui/pending.py, datameta/security/authz.py, datameta/static/js/submit.js, datameta/templates/submit.pt, setup.py
* Invalid `None` comparison preventing users with the primary key `0` (me 😆 ) from data acccess
* "Failed metadatasets" and "Metadata explanation" UI elements were invisible
* The submit view was expecting an invalid MetaDataSetResponse schema
=> Urgent fixes

datameta/api/metadata.py, datameta/api/metadatasets.py, datameta/api/submissions.py, datameta/api/ui/convert.py, datameta/api/ui/pending.py, datameta/linting.py, datameta/static/js/admin.js, datameta/static/js/submit.js, datameta/static/js/view.js
This patch (hopefully) fixes everything that breaks when adding service metadata (metadata with a service associated)
=> Service-Metadata UI and backend adjustments

datameta/api/metadata.py, datameta/api/openapi.yaml, datameta/static/js/admin.js
=> Adding Services to metadata backend and ui

datameta/api/__init__.py, datameta/api/metadatasets.py, datameta/api/openapi.yaml, datameta/api/submissions.py, datameta/api/ui/convert.py, datameta/api/ui/pending.py, datameta/api/ui/view.py, datameta/security/authz.py, datameta/utils.py, datameta/validation.py
Adds a new endpoint `POST:service-execution` where service execution results can be reported.
=> Add new Endpoint `POST:service-execution`

datameta/api/download.py, datameta/api/openapi.yaml
this should address issue #454
=> implemented changes

conf/docker_development.ini, conf/docker_production.ini
load 2fa settings from environment
=> update configs for container

datameta/defaults/appsettings.yaml, datameta/templates/layout-minimal.pt, datameta/templates/layout.pt, datameta/views/default.py, datameta/views/forgot.py, datameta/views/login.py, datameta/views/register.py, datameta/views/setpass.py, datameta/views/settfa.py, datameta/views/tfa.py
Targets #338
Missing name of current page (e.g. Login)
Name exists
=> Fix page title

conf/ci.ini, conf/development.ini, conf/docker_development.ini, conf/docker_production.ini, conf/production.ini, datameta/api/files.py, datameta/api/register.py, datameta/api/ui/admin.py, datameta/api/ui/convert.py, datameta/api/ui/forgot.py, datameta/email/__init__.py, datameta/samplesheet.py, datameta/security/__init__.py, datameta/settings.py, datameta/siteid.py, datameta/storage.py, datameta/views/default.py, datameta/views/login.py, datameta/views/tfa.py, setup.py
PR adds `JsonFormatter ` from `python-json-logger` to enable log serialization.
=> Add json logger

datameta/templates/settfa.pt, datameta/templates/tfa.pt
This PR disables autocomplete for OTP forms
=> Disable autocomplete for OTP forms

datameta/templates/404.pt, datameta/templates/minimal.pt
PR updates template `minimal.pt` , which was missed in #491 and #490
=> Fix minimal template

datameta/api/register.py
=> change keys, `name` is reserved

datameta/api/metadatasets.py, datameta/api/submissions.py
Add logging to MetaDataSet endpoints as required for CoGDat
- Auslesen von Falldaten
- neue Falldaten
=> Add logging to MetaDataSest

setup.py
=> Hotfix AttributeError: 'SvgPathFillImage' object has no attribute 'make_path'

datameta/security/__init__.py, datameta/templates/forgot.pt, datameta/views/login.py, datameta/views/tfa.py
- log only when failed attempts was > 0
=> Fix clear login attempts logging

datameta/security/tfaz.py, datameta/templates/settfa.pt, setup.py
=> Update qr code injection

datameta/defaults/appsettings.yaml, datameta/settings.py, datameta/templates/404.pt, datameta/templates/forgot.pt, datameta/templates/layout-minimal.pt, datameta/templates/layout.pt, datameta/templates/login.pt, datameta/templates/minimal.pt, datameta/templates/register.pt, datameta/templates/settfa.pt, datameta/templates/tfa.pt, datameta/views/default.py
- This PR refactors the injection of appsettings in the global namespace of the template system
- all appsettings which starts with prefix `renderer_` are injected
- Main purpose is to generalize and simplify the injection procedure
=> Refactor appsetting injection
